plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'
    id "me.modmuss50.mod-publish-plugin" version "2.0.0"
}
configurations {
    fabricApiJars
}

def extractFabricApi = tasks.register('extractFabricApi', Copy) {
    from {
        configurations.fabricApiJars.files.collect { jar ->
            zipTree(jar).matching {
                include 'META-INF/jars/*.jar'
                exclude 'META-INF/jars/*data-generation*'
                exclude 'META-INF/jars/*gametest*'
            }
        }
    }
    into layout.buildDirectory.dir("fabric-api-jars")
    eachFile { it.path = it.name }
    includeEmptyDirs = false
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    fabricApiJars "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation fileTree(dir: layout.buildDirectory.dir("fabric-api-jars"), include: ['*.jar']).builtBy(extractFabricApi)
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}
publishMods {
    file = jar.archiveFile
    changelog = rootProject.file("CHANGELOG.md").text
    type = STABLE
    version = "${project.property('version')}"
    modLoaders.add("fabric")
    modLoaders.add("quilt")

    curseforge {
        displayName = file.map { it.asFile.name }
        projectId = property("curseforge_id")
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        changelogType = "markdown"

        minecraftVersions.addAll(property("publish_minecraft_versions").split(",") as List<String>)

        client = true
        server = false
        requires("fabric-api")
    }

    modrinth {
        displayName = "Better FireFlies ${project.property('version')}"
        projectId = property("modrinth_id")
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")

        minecraftVersions.addAll(property("publish_minecraft_versions").split(",") as List<String>)

        requires("fabric-api")
    }
}