# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.1-26.2
group=com.atom.FireFly
java_version=25

# Common
minecraft_version=26.2
mod_name=FireFly
mod_author=Atom
mod_id=firefly
license=CC0-1.0
credits=
description=Add FireFly in different biomes. \nAccepts multilines.
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-2

# Fabric
fabric_version=0.160.0+26.2
fabric_loader_version=0.18.2

# Forge
forge_version=51.0.17
forge_loader_version_range=[51,)

# NeoForge
neoforge_version=26.2.0.88
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=C:\\Users\\allew\\.jdks\\temurin-25.0.3

# PublishMods
curseforge_id=1629782
modrinth_id=WpcP0H59
publish_minecraft_versions=26.2
